Repository snaptec/openWB, pull requests merged in 2021-01, with the labels that each got.

#844 Logging and Bug Fixing Mercedes EQ SoC Module
  modules/soc_eq/callback_lp1.php
  modules/soc_eq/callback_lp2.php
  modules/soc_eq/main.sh
  modules/soc_eq/soc.py
Labels: Bugfix, enhancement

#849 unified timestamp in soc.log
  modules/soc_bluelink/main.sh
  modules/soc_eq/main.sh
  modules/soc_eq/soc.py
  modules/soc_evnotify/main.sh
  modules/soc_from_elastic/main.sh
  modules/soc_http/main.sh
  modules/soc_i3/main.sh
  modules/soc_i3s1/main.sh
  modules/soc_id/main.sh
  modules/soc_kia/main.sh
  modules/soc_leaf/main.sh
  modules/soc_leaf/soc.py
  modules/soc_leafs1/main.sh
  modules/soc_leafs1/soc.py
  modules/soc_manual/main.sh
  modules/soc_myrenault/main.sh
  modules/soc_tesla/main.sh
  modules/soc_volvo/main.sh
  runs/atreboot.sh
Labels: Bugfix

#860 Use string literal instead of undefined variable
  runs/smarthomehandler.py
Labels: Bugfix

#773 implement "openWB Buchse" for isss
  runs/atreboot.sh
  runs/buchse.py
  runs/isss.py
Labels: enhancement, waiting for feedback

#865 filter SoC 0%
  modules/soc_bluelink/bluelinksoc.py
  modules/soc_bluelink/main.sh
Labels: Bugfix, waiting for feedback

#871 enhancement of mqttll-module
  modules/mqttlllp2/main.sh
  modules/mqttlllp3/main.sh
  runs/mqttsub.py
  web/settings/modulconfiglp.php
Labels: enhancement

#920 Fehlerbehandlung verbessert und Bugfix
  .gitignore
  modules/et_tibber/stromtarifinfo/infopage.html
  modules/et_tibber/stromtarifinfo/tibber.js
  modules/et_tibber/tibbergetprices.py
  web/themes/EvenDarker/theme.html
  web/themes/Gauges/electricityPriceChart.js
  web/themes/Gauges/theme.html
  web/themes/dark/electricityPriceChart.js
  web/themes/dark/theme.html
Labels: Bugfix

#926 Add more logging messages to AVM Home Automation module
  modules/smarthome/avmhomeautomation/avmcommon.py
Labels: enhancement

#911 SoC Peugeot: kombiniere manuell+berechnung und PSA modul, ersetzt #899
  modules/soc_mypeugeot/main.sh
  runs/atreboot.sh
  web/settings/modulconfiglp.php
Labels: change requested, enhancement

#937 MyOpel SoC Module: add man+calc option
  .gitignore
  modules/soc_myopel/main.sh
  modules/soc_mypeugeot/main.sh
  runs/updateConfig.sh
  web/settings/modulconfiglp.php
Labels: enhancement
