Repository snaptec/openWB, pull requests merged in 2021-04, with the labels that each got.

#1270 Pingcheck enhancement
  runs/pingcheck.sh
Labels: enhancement

#1271 SoC HTTP Intervallvorgabe (beta V2)
  modules/soc_http/main.sh
  runs/updateConfig.sh
  web/settings/modulconfiglp.php
Labels: change requested, enhancement

#1123 Verbraucherzähler Fronius und allgemein json
  modules/smarthome/fronius/watt.py
  modules/smarthome/json/watt.py
Labels: change requested, enhancement

#1262 Avoid hardcoding 127.0.0.1:80
  loadvars.sh
Labels: Bugfix, good first issue

#1289 Mindestlaufzeit nach CP Unterbrechung
  nurpv.sh
  regel.sh
  runs/updateConfig.sh
  web/settings/misc.php
Labels: enhancement

#1057 Solaredge modbus TCP port config added
  modules/bezug_solaredge/main.sh
  modules/bezug_solaredge/solaredge.py
  runs/updateConfig.sh
  web/settings/modulconfigevu.php
Labels: change requested, enhancement

#1310 Hinweis auf Go-e Firmware Update 0.40
  web/settings/modulconfiglp.php
Labels: change requested

#1309 go-e API: neuer Befehl zur Stromvorgabe
  goecheck.sh
  runs/set-current.sh
Labels: change requested, enhancement

#1338 ermöglicht das Senden der aktuellen PV-Leistung als Float
  runs/mqttsub.py
Labels: enhancement, question
