Repository snaptec/openWB, pull requests merged in 2021-05, with the labels that each got.

#1353 Prevent concurrent openwb.conf modifications from mqttsub.py
  runs/mqttsub.py
Labels: Bugfix

#1362 Alternative EVU+Batterie-Module für Solarwatt/MyReserve-Geräte mit Gateway
  modules/bezug_solarwatt/main.sh
  modules/speicher_solarwatt/main.sh
  modules/wr_solarwatt/main.sh
  runs/updateConfig.sh
  web/settings/modulconfigbat.php
Labels: enhancement

#1339 Modulkonfiguration EVU - Fronius Smart/S0 Meter
  modules/bezug_fronius_sm/froniusloadmeterdata.php
  web/settings/modulconfigevu.php
Labels: enhancement

#1392 Read and MQTT publish meter serial numbers
  modules/mpm3pmll/readall.py
  modules/mpm3pmll/readmpm3pm.py
  modules/sdm120modbusSocket/readsdm.py
  runs/pubmqtt.sh
Labels: enhancement

#1404 Fix openwb.conf manipulations with sed when running in Docker
  modules/soc_tesla/main.sh
  runs/cronnightly.sh
  runs/replaceinconfig.sh
  runs/senddebug.sh
  runs/updateConfig.sh
  runs/wlanconnect.sh
Labels: enhancement

#1383 Wiki zur Navbar hinzufügen
  web/hilfe/navbar.php
  web/settings/navbar.html
  web/themes/navbar.html
Labels: change requested
