Repository snaptec/openWB, pull requests merged in 2021-03, with the labels that each got.

#1116 fix display of "Datenserien für Diagramme"
  web/settings/mqtt.php
Labels: Bugfix

#1105 get own IP Adress
  runs/atreboot.sh
  runs/cron5min.sh
  runs/pingcheck.sh
Labels: change requested, enhancement

#1142 Neues VAG SoC Modul - VW, ID, AUDI, Seat, Skoda, Porsche. Abfrageintervalle frei einstellbar
  modules/soc_vag/main.sh
  modules/soc_vaglp2/main.sh
  runs/updateConfig.sh
  web/settings/modulconfiglp.php
Labels: change requested, enhancement

#1089 fix autolock: respect waitUntilFinished setting
  processautolock.sh
Labels: Bugfix

#1177 Möglichkeit mehrere MQTT-Brücken einzurichten
  web/settings/mqtt.php
  web/tools/savemqtt.php
Labels: enhancement

#1191 new WE514 module for smarthome 2.0
  modules/smarthome/we514/watt.py
  runs/mqttsub.py
  runs/smarthomehandler.py
  web/settings/smarthomeconfig.php
Labels: change requested, enhancement

#1075 Viel bzw. wenig Überschuss beim Umschalten berechnen statt harter Werte
  u1p3p.sh
Labels: change requested, enhancement

#1183 added Modul for Studer-Innotec
  .gitignore
  modules/speicher_studer/main.sh
  modules/speicher_studer/studer_speicher.py
  web/settings/modulconfigbat.php
Labels: change requested, enhancement

#1211 fixed ladelog error to include nachtladen
  ladelog.sh
Labels: Bugfix, enhancement

#1202 Update curl call to support password with spaces
  modules/bezug_discovergy/main.sh
Labels: enhancement, waiting for feedback

#1203 Update curl call to support spaces in password
  modules/wr_discovergy/main.sh
Labels: enhancement, waiting for feedback

#1204 Allow spaces for discovergypass
  openwb.conf
Labels: change requested, enhancement

#1092 WebHooks beim Beginn und Beenden der Ladung #884
  hook.sh
  runs/initRamdisk.sh
  runs/updateConfig.sh
  web/settings/smarthome.php
  web/tools/savesmarthome.php
Labels: change requested, enhancement

#1086 Initial support for socket in slave mode
  loadvars.sh
  modules/sdm120modbusSocket/main.sh
  modules/sdm120modbusSocket/readsdm.py
  regel.sh
  rfidtag.sh
  runs/atreboot.sh
  runs/initRamdisk.sh
  runs/mqttsub.py
  runs/pubmqtt.sh
  runs/standardSocket.py
  runs/updateConfig.sh
  slavemode.sh
Labels: enhancement

#1235 Add manual SoC calulation for Kia
  modules/soc_kia/kiasoc.py
  modules/soc_kia/main.sh
  runs/updateConfig.sh
  web/settings/modulconfiglp.php
Labels: enhancement
