Repository snaptec/openWB, pull requests merged in 2022-10, with the labels that each got.

#2294 rewrite isss daemon
  packages/helpermodules/compatibility.py
  packages/modules/common/abstract_chargepoint.py
  packages/modules/common/b32.py
  packages/modules/common/component_state.py
  packages/modules/common/evse.py
  packages/modules/common/lovato.py
  packages/modules/common/modbus.py
  packages/modules/common/mpm3pm.py
  packages/modules/common/sdm.py
  packages/modules/common/store/_chargepoint.py
  packages/modules/internal_openwb/__init__.py
  packages/modules/internal_openwb/chargepoint_module.py
  packages/modules/internal_openwb/socket.py
  runs/initRamdisk.sh
  runs/isss.py
Labels: enhancement, help wanted

#2393 Enphase inverter and counter (no battery yet)
  modules/bezug_enphase/main.sh
  modules/wr_enphase/main.sh
  packages/modules/enphase/__init__.py
  packages/modules/enphase/config.py
  packages/modules/enphase/counter.py
  packages/modules/enphase/device.py
  packages/modules/enphase/inverter.py
  runs/updateConfig.sh
  web/settings/modulconfigevu.php
  web/settings/modulconfigpv.php
Labels: enhancement, change requested

#2444 Socket: prevent the motor from burning out
  runs/triginit.py
Labels: Bugfix

#2447 fix isss for duo
  runs/services.sh
Labels: bug

#2462 consider dc production for hybrid systems
  packages/modules/common/component_state.py
  packages/modules/sma_sunny_boy/device.py
  packages/modules/sma_sunny_boy/inverter.py
  packages/modules/sma_sunny_boy/sma_sunny_boy_test.py
  packages/modules/solaredge/device.py
  packages/modules/solaredge/inverter.py
Labels: Bugfix

#2466 fix openWB Pro cp 4-8
  loadvars.sh
Labels: Bugfix

#2445 option for Sungrow SG with WiNet-dongle
  packages/modules/sungrow/counter.py
  packages/modules/sungrow/device.py
  packages/modules/sungrow/version.py
  web/settings/modulconfigevu.php
Labels: enhancement
