Repository snaptec/openWB, pull requests merged in 2022-01, with the labels that each got.

#1880 E3DC Bezugsmodul auf V2 Syntax umgestellt
  modules/bezug_e3dc/e3dc.py
  modules/bezug_e3dc/main.sh
Labels: change requested

#1947 fetch vehicle list on demand only
  web/css/settings_style.css
  web/settings/modulconfiglp.php
Labels: waiting for feedback

#1958 SolarView: Allow configuration of command
  modules/wr_solarview/main.sh
  modules/wr_solarview/solarview.py
  runs/updateConfig.sh
  web/settings/modulconfigpv.php
Labels: enhancement, Bugfix

#1957 Victron module: Fixed register reading voltage L3 + added power reading per phase
  packages/modules/victron/counter.py
Labels: Bugfix
